language: go
go_import_path: github.com/getamis/istanbul-tools
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      go: 1.7.6
      script:
        - go test -parallel 4 $(glide novendor | grep -v "\.\/tests\/\.\.\.") && cd tests && ginkgo -p

    # These are the latest Go versions.
    - os: linux
      dist: trusty
      sudo: required
      go: 1.8.3
      script:
        - go test -parallel 4 $(glide novendor | grep -v "\.\/tests\/\.\.\.") && cd tests && ginkgo -p

services:
  - docker

install:
  - go get github.com/Masterminds/glide
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - go test $(glide novendor)

notifications:
    slack: maicoin:p2HicxEGvZveE900zgacSYwL
