language: go
go_import_path: github.com/getamis/istanbul-tools
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      go: 1.7.6
      script:
        - travis_wait 120 go test -v $(glide novendor) --timeout 120m

    # These are the latest Go versions.
    - os: linux
      dist: trusty
      sudo: required
      go: 1.8.3
      script:
        - travis_wait 120 go test -v $(glide novendor) --timeout 120m

services:
  - docker

install:
  - go get github.com/Masterminds/glide
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - travis_wait 120 go test -v $(glide novendor) --timeout 120m

notifications:
    slack: maicoin:p2HicxEGvZveE900zgacSYwL
