kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    environment: {{ template "environment" . }}
data:
{{- if .Values.fileName }}
{{ template "staticNodes" . }}
{{- end }}